### ISSUE TITLE
Read -re action failed with exit code 1

### ISSUE THREAD

**Issue by hailthedreadprince** [chrultrabook/crap#5]
While running the crap on a c223 chromebook, the display of the available actions shows, then the program immediately stops showing that the read -re action failed with exit code 1.

**Comment by BinBashBanana** [comment]
Which version of ChromeOS are you running?

**Comment by hailthedreadprince** [comment]
I'm not sure what version I was running at the time, but now I am running version 126.0.6478.222. When I tried to reproduce the glitch it instead mirrored what happened to altxm. I did however manage to use crap successfully by running it from within arch.

**Comment by BinBashBanana** [comment]
This occurs when you pipe the script into bash, a check will be added in the next version.
