### ISSUE TITLE
Input 1 kicks to VT2 login and kills network

### ISSUE THREAD

**Issue by altxm** [chrultrabook/crap#6]
This may not be the right spot for what I've got so please let me know if this should be on support forum

Machine is a Dell Latitude 5400 Enterprise (SARIEN board). Been following along the chrultrabook docs up to running crap. I hit 1 to reformat and the below is the last screen before it kicks me back to the VT2 login screen. Checking env shows network interfaces are down, can bring them back up but no idea how to reconnect to network. Trying to exit back to the browser freezes everything requiring hard reset. Sorry about the resolution - says Unmounting stateful then angup(?)

![thumbnail_1000001203](https://github.com/user-attachments/assets/61d7e3f4-e926-4b09-af2e-d20351b49e37)

I've tried running crap from the arch instance I'm planning to install and it fails out since it can't find cgpt

Also stored a local copy of the script to try running again after it kicks me back to VT2 login. This will get me to the main menu same as above, choosing 1 terminates the script straight away. Image below - says Unmounting stateful then Terminated

![thumbnail_1000001207](https://github.com/user-attachments/assets/b5ddb2f0-3883-4bc2-b7c6-833d79582a95)

Any ideas or assistance much appreciated <3

**Comment by altxm** [comment]
Workaround:

If you're running Arch then hook up to AUR and get vboot-utils for cgpt then run CRAP from there
[AUR setup](https://aur.chaotic.cx/docs)
`$ pacman -Sy chaotic-aur/vboot-utils`

(thanks to sadlerm)

**Comment by BinBashBanana** [comment]
Which version of ChromeOS are you running?

**Comment by therealloudking** [comment]
I used ventoy with kali live everything and after connecting to wifi and logging in as root. I ran the script and everything worked.

**Comment by tuctboh** [comment]
Same thing for me. 

Version 130.0.6723.101 (Official Build) (64-bit)
RW_LEGACY install
NOSPIKE hardware
Looking to install Fedora 41 Desktop


https://github.com/user-attachments/assets/f565c86a-1c19-415b-af27-be619b975e5d

**Comment by BinBashBanana** [comment]
Ah, I didn't think people would run this with sudo. Log in as root and try again, I'll add a check for this.

**Comment by BinBashBanana** [comment]
Fixed!
